# Generated by Django 3.0.5 on 2020-08-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_generalanamnesis_w3a'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalanamnesis',
            name='w3a',
            field=models.CharField(choices=[('obecne', 'obecne'), ('nieobecne', 'nieobecne')], default='nieobecne', max_length=255),
            preserve_default=False,
        ),
    ]
