# Generated by Django 3.0.5 on 2020-08-20 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_generalanamnesis_w3a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phisicalexamination',
            name='patient',
        ),
    ]
