# Generated by Django 3.0.5 on 2020-08-20 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_phisicalexamination_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='phisicalexamination',
            name='patient',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Patient'),
            preserve_default=False,
        ),
    ]
