# Generated by Django 3.0.5 on 2020-08-20 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_patient_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsychaitricAssesment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b1', models.CharField(max_length=255)),
                ('b2', models.CharField(max_length=255)),
                ('b3', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Patient')),
            ],
        ),
    ]
